### ISSUE TITLE
PARD Data

### ISSUE THREAD

**Issue by luqmaan** [open-austin/liberate-the-data#3]
We use data from http://services.arcgis.com/0L95CJ0VTaxqcmED/ for Austin Park Equity and Austin Green Map.

There are some problems with it though:
- We don't know what the license on the data is.
- We don't know how frequently the data is updated.
- We have to use funky queries to extract the data (select \* from where 1 = 1). Its a little easier to just download geojson files with all the data.

Related to https://github.com/open-austin/austingreenmap/issues/50

**Comment by mateoclarke** [comment]
Good news, Matt Esquibel from CoA CTM responded back to us and said that per City of Austin GIS Manager, Ross Clark, the data on ArcGIS is subject to the same CoA Open Data Terms of Use Policy as data.austintexas.gov. This covers the first concern.

cc/ @wilsaj 

[park_data.pdf](https://github.com/open-austin/liberate-the-data/files/109209/park_data.pdf)

**Comment by wilsaj** [comment]
![](https://media.giphy.com/media/3o85xzwOcKkOw67ywg/giphy.gif)

**Comment by johnclary** [comment]
:+1:
